import { ArrowUpRight, Quote } from 'lucide-react'
import { DirectContactCard, PageFrame } from '@/components/site-shell'

const stories = [
  { name: 'Riya Mehta', detail: 'MBA — Symbiosis International University', quote: 'I was confused about which college would be right for me. The team understood my preferences and helped me shortlist the options that matched my career goals.' },
  { name: 'Arjun Shah', detail: 'IIM Indore · PGP', quote: 'The preparation was structured, honest, and completely tailored to my goals.' },
  { name: 'Neha Kapoor', detail: 'SPJIMR Mumbai · PGDM', quote: 'I went from feeling overwhelmed to having a plan I could actually follow.' },
  { name: 'Aarav Sharma', detail: 'MBA — NMIMS Mumbai', quote: 'MBAConnectIndia helped me understand my options and guided me throughout the admission process. The counselling was clear, practical, and really helped me make a confident decision.' },
  { name: 'Kunal Verma', detail: 'MBA — Manipal Academy of Higher Education', quote: 'The guidance I received made the entire admission process much easier. I got clarity about the college, course, application process, and important deadlines.' },
  { name: 'Ananya Gupta', detail: 'MBA — Christ University', quote: 'The counselling session gave me a much better understanding of my MBA options. I really appreciated the personalised approach and straightforward guidance.' },
  { name: 'Rahul Malhotra', detail: 'MBA — Amity University', quote: 'MBAConnectIndia made the college selection process much less stressful. Their guidance helped me compare different options and choose the one that suited me best.' },
  { name: 'Sneha Kapoor', detail: 'MBA — UPES Dehradun', quote: 'I had several doubts about choosing the right MBA programme. The counselling team patiently answered my questions and helped me move forward with much more confidence.' },
  { name: 'Aditya Jain', detail: 'MBA — Great Lakes Institute of Management', quote: 'The entire experience was smooth and informative. I received useful guidance at every stage and had much more clarity about my admission decision.' },
  { name: 'Ishita Agarwal', detail: 'MBA — Welingkar Institute of Management', quote: 'The personalised counselling was exactly what I needed. Instead of giving generic suggestions, the team helped me understand which options were most suitable for my profile.' },
]
export default function AchievementsPage() { return <PageFrame><main><section className="bg-secondary"><div className="mx-auto max-w-7xl px-5 py-20 sm:px-8 md:py-28"><p className="mb-4 text-sm font-bold uppercase tracking-[0.16em] text-primary">Student achievements</p><h1 className="max-w-3xl text-balance text-4xl font-bold tracking-tight text-ink sm:text-6xl">Progress worth <span className="text-primary">celebrating.</span></h1><p className="mt-6 max-w-2xl text-lg leading-8 text-muted-foreground">Behind every admit is a personal story of effort, uncertainty, and growth. We are proud to be part of those stories.</p></div></section><section className="mx-auto max-w-7xl px-5 py-20 sm:px-8 md:py-28"><div className="mb-10 flex items-end justify-between gap-5"><div><p className="mb-3 text-sm font-bold uppercase tracking-[0.16em] text-primary">In their words</p><h2 className="text-3xl font-bold tracking-tight text-ink sm:text-4xl">The people behind the outcomes.</h2></div><span className="hidden font-mono text-sm text-muted-foreground sm:block">01 — 10</span></div><div className="grid gap-5 md:grid-cols-3">{stories.map((story) => <article key={story.name} className="flex min-h-72 flex-col justify-between rounded-2xl border border-border p-6"><Quote className="size-7 text-accent" fill="currentColor" /><p className="mt-8 text-lg font-semibold leading-8 text-ink">“{story.quote}”</p><div className="mt-8 border-t border-border pt-4"><p className="font-bold text-ink">{story.name}</p><p className="mt-1 text-sm text-muted-foreground">{story.detail}</p></div></article>)}</div></section><section className="bg-ink text-primary-foreground"><div className="mx-auto grid max-w-7xl gap-10 px-5 py-20 sm:px-8 md:grid-cols-[1.2fr_.8fr] md:items-center md:py-24"><div><p className="mb-3 text-sm font-bold uppercase tracking-[0.16em] text-accent">Your story next</p><h2 className="max-w-2xl text-3xl font-bold tracking-tight sm:text-4xl">The result matters. So does the journey.</h2></div><a href="tel:+919876543210" className="inline-flex w-fit items-center gap-2 rounded-lg bg-accent px-5 py-3.5 text-sm font-bold text-ink">Start your journey <ArrowUpRight className="size-4" /></a></div></section><section className="mx-auto max-w-7xl px-5 py-20 sm:px-8"><DirectContactCard /></section></main></PageFrame> }
